### ISSUE TITLE
Clean meghadutam (Kale edition) XML file

### ISSUE THREAD

**Issue by kiranlakkur** [ambuda-org/gretil#1]
As part of expanding texts available on ambuda, clean meghadutam TEI file(Kale Edition - sa_kAlidAsa-meghadUta-edkale).

**Comment by kiranlakkur** [comment]
Hi @akprasad,

I have cleaned meghadūtam TEI XML file(Kale edition. Filename: sa_kAlidAsa-meghadUta-edkale.xml). Please see [here](https://github.com/ambuda-project/gretil/compare/main...kiranlakkur:text/meghadutam)

Unfortunately, I don't know much of Sanskrit. I can read devanāgari and can understand only a few words. I have tried my best to sanitize the data.

As part of cleaning the TEI file, I have done the following:

- Original file didn't have any sections in it. So, I have added two `<div>` blocks (one for pūrvamegha and one for uttaramegha). I haven't added the **`type`** attribute to the  `<div>`s, as I was not sure if they should be called sargā, kānḍa or parva. 
- pādās of verses were not structured correctly. First line pāda of all verses was wrapped in `<p>` tags and rest were wrapped in `<lg>`. This has been corrected.
- There was no `<head>` tag in the original file. So I have added 2 `<head>` tags (one for pūrvamegha and one for uttaramegha).
- Verses 1.19a and 2.45a in the original TEI file are marked as prakṣipta in the notes. I have retained them and renumbered as 1.20 and 2.45
- 4th pādā of verse 2.30 in the original file was not correct. I have corrected phrase **sābhre.ahnīva** to **sābhhre'hnīva**


I have tested this in my local to see if the text renders correctly. It looks good to me. Please see below:


> ![image](https://user-images.githubusercontent.com/26911745/178102764-139af8c2-6a2a-456c-96c6-0958b376076c.png)

Please let me know if this changes look good to raise a PR.

**Comment by akprasad** [comment]
Wonderful! Awesome that you stepped in here. Thank you.

Some comments:

- For the xml_id, I prefer the style `KalMgD.1.23"` over `KalMgD_1.23"`.
- Try to preserve the same indenting as the `main` file so that the diff stays small.
- I think Kale preserves verse numbers and I'd like to do the same here. That is, where GRETIL does `// 1.1 //` we should do `|| 1 ||` instead of just `||`.
- We can retain the प्रक्षिप्त verses, but rather than renumber them, let's wrap them in `<del>` elements instead (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COEDADD). The reason is that I want to reflect the source text's numbering scheme as accurately as possible.

**Comment by akprasad** [comment]
Also -- while we're editing this file, let's replace the typo `vidhunvantaṃ` with the original `vidyutvantaṃ`

**Comment by kiranlakkur** [comment]
Hi @akprasad,

Thanks for your comments. I have now made the changes based on your comments. Please see [here](https://github.com/ambuda-project/gretil/compare/main...kiranlakkur:text/meghadutam)

I have wrapped 1.19a and 2.45a in `<del>`. But when trying to load the file in my local setup, seed for gretil texts was failing as it  cannot handle `<del>` blocks. I am not sure what approach should be taken here. Do you have a preferred approach as to how this should be handled. This will help me when I pick other texts.

For now, I have changed the gretil seed in my setup to ignore `<del>` blocks.

Additionally, following text corrections have been made:

Verse 1.43 : `so.api` to `so'api`
Verse 2.1 : `vidhunvantaṃ` to `vidyutvantaṃ`
Verse 2.30 : `sābhhre.hnīva` to  `sābhhre'hnīva`
Verse 2.31 : `svapnajo.apīti` to `svapnajo'pīti`

I have tested this in my local to see if the text renders correctly. It looks good to me.

I wrote a small script(using ElementTree) to make the corrections and clean the data in my first try. I just used the output file of this script and hence the indentation was off. 

Please let me know if these changes look good to raise a PR.

**Comment by akprasad** [comment]
> For now, I have changed the gretil seed in my setup to ignore `<del>` blocks.

I think this is the correct approach for now. We can revisit it later and perhaps render these verses in a different style.

For the corrections:

- `so'api` shoudl be `so'pi`
- `sābhhre` should be `sābhre`

Otherwise, LGTM and feel free to create a PR.

**Comment by akprasad** [comment]
And in the future, feel free to create a PR directly -- it will be less work for you!

**Comment by kiranlakkur** [comment]
Thank you. Raised a PR. I have made the corrections to `so'api` and `sābhhre` as suggested.

I am new to all this, so don't want to cause any trouble :)

**Comment by kiranlakkur** [comment]
https://github.com/ambuda-project/gretil/pull/2
